import json
import boto3
import os
import subprocess
import tempfile
import shutil
from urllib.parse import urlparse
import requests

AWS_REGION = os.environ.get('AWS_REGION', os.environ.get('AWS_DEFAULT_REGION', 'us-east-1'))
bedrock = boto3.client('bedrock-runtime', region_name=AWS_REGION)
sqs = boto3.client('sqs', region_name=AWS_REGION)

# Queue URL injected by CloudFormation env vars at deploy time.
QUEUE_URL = os.environ.get('QUEUE_URL', '')
BEDROCK_MODEL = os.environ.get('BEDROCK_MODEL_ID', 'amazon.nova-2-lite-v1:0')

GITHUB_TOKEN = os.environ.get('GITHUB_TOKEN', '')


def clone_repo(repo_url, branch, token):
    tmp_dir = tempfile.mkdtemp()

    if token:
        parsed = urlparse(repo_url)
        auth_url = f"{parsed.scheme}://x-access-token:{token}@{parsed.netloc}{parsed.path}"
    else:
        auth_url = repo_url

    cmd = ['git', 'clone', '--depth', '1', '--branch', branch, auth_url, tmp_dir]
    try:
        subprocess.run(cmd, capture_output=True, check=True, timeout=120)
        return tmp_dir
    except subprocess.CalledProcessError as e:
        print(f"Git clone failed: {e.stderr.decode()}")
        raise


def get_changed_files(repo_path, base_sha, head_sha):
    try:
        cmd = ['git', 'diff', '--name-only', base_sha, head_sha]
        result = subprocess.run(cmd, cwd=repo_path, capture_output=True, check=True)
        files = result.stdout.decode().strip().split('\n')
        return [f for f in files if f and not f.endswith('.lock')]
    except subprocess.CalledProcessError as e:
        print(f"Git diff failed: {e.stderr.decode()}")
        return []


def analyze_with_nova(code_content, filepath):
    if len(code_content) > 4000:
        code_content = code_content[:4000] + "\n... (truncated)"

    prompt = f"""You are an expert code reviewer analyzing a pull request.

File: {filepath}

Code:

{code_content}


Analyze this code for:
1. **Security vulnerabilities** - SQL injection, hardcoded secrets, XSS, insecure dependencies
2. **Code quality** - readability, maintainability, best practices
3. **Performance issues** - inefficient loops, memory leaks, slow operations

Return your findings as a JSON array with this exact structure:
[
  {{
    "line": 42,
    "severity": "high",
    "category": "security",
    "message": "Hardcoded API key detected"
  }}
]

If no issues found, return: []"""

    try:
        response = bedrock.converse(
            modelId=BEDROCK_MODEL,
            messages=[{
                "role": "user",
                "content": [{"text": prompt}]
            }],
            inferenceConfig={
                "maxTokens": 2000,
                "temperature": 0.1
            }
        )

        response_text = response['output']['message']['content'][0]['text']

        try:
            start = response_text.find('[')
            end = response_text.rfind(']') + 1
            if start != -1 and end > start:
                json_str = response_text[start:end]
                return json.loads(json_str)
        except Exception:
            pass

        return []

    except Exception as e:
        print(f"Bedrock error: {str(e)}")
        return []


def post_github_review(repo, pr_number, findings, token):
    if not token:
        print("No GitHub token provided, skipping post")
        return

    headers = {
        'Authorization': f'token {token}',
        'Accept': 'application/vnd.github.v3+json'
    }

    if not findings:
        url = f'https://api.github.com/repos/{repo}/issues/{pr_number}/comments'
        data = {
            'body': '\u2705 **AI Review Complete**\n\nNo issues detected in this PR!'
        }
        try:
            requests.post(url, headers=headers, json=data)
            print("Success message posted")
        except Exception as e:
            print(f"Error posting comment: {str(e)}")
        return

    comments = []
    for finding in findings:
        emoji = '\U0001F534' if finding.get('severity') == 'high' else '\U0001F7E1' if finding.get('severity') == 'medium' else '\U0001F535'
        comments.append(
            f"{emoji} **{finding.get('severity', 'medium').upper()}**: {finding.get('message', '')}"
        )

    summary = f"""## \U0001F916 AI Code Review

Found {len(findings)} issue(s):

{chr(10).join(comments)}

---
*Generated by Amazon Nova AI*
"""

    url = f'https://api.github.com/repos/{repo}/issues/{pr_number}/comments'
    data = {'body': summary}

    try:
        response = requests.post(url, headers=headers, json=data)
        print(f"Review posted: {response.status_code}")
    except Exception as e:
        print(f"Error posting review: {str(e)}")


def handler(event, context):
    print(f"Received SQS event with {len(event['Records'])} records")

    for record in event['Records']:
        receipt_handle = record['receiptHandle']

        try:
            payload = json.loads(record['body'])

            action = payload.get('action')
            pr_number = payload.get('number')
            repo_name = payload.get('repository', {}).get('full_name')
            clone_url = payload.get('repository', {}).get('clone_url')
            pr_title = payload.get('pull_request', {}).get('title', 'No title')

            if action not in ['opened', 'synchronize', 'reopened']:
                print(f"Skipping action: {action}")
                sqs.delete_message(QueueUrl=QUEUE_URL, ReceiptHandle=receipt_handle)
                continue

            print(f"Processing PR #{pr_number}: {pr_title} from {repo_name}")

            head_sha = payload.get('pull_request', {}).get('head', {}).get('sha')
            base_sha = payload.get('pull_request', {}).get('base', {}).get('sha')
            head_ref = payload.get('pull_request', {}).get('head', {}).get('ref')

            if not all([head_sha, base_sha, head_ref]):
                print("Missing commit info, skipping")
                sqs.delete_message(QueueUrl=QUEUE_URL, ReceiptHandle=receipt_handle)
                continue

            print(f"Cloning {repo_name} branch {head_ref}")
            repo_path = clone_repo(clone_url, head_ref, GITHUB_TOKEN)

            try:
                changed_files = get_changed_files(repo_path, base_sha, head_sha)
                print(f"Found {len(changed_files)} changed files")

                code_extensions = {'.py', '.js', '.ts', '.java', '.go', '.rb', '.php', '.c', '.cpp', '.h', '.cs', '.rs'}
                code_files = [f for f in changed_files if any(f.endswith(ext) for ext in code_extensions)]
                print(f"Analyzing {len(code_files)} code files")

                all_findings = []

                for filepath in code_files[:10]:
                    try:
                        full_path = os.path.join(repo_path, filepath)
                        if os.path.isfile(full_path):
                            with open(full_path, 'r', encoding='utf-8') as f:
                                content = f.read()

                            if content.strip():
                                print(f"Analyzing {filepath}")
                                findings = analyze_with_nova(content, filepath)
                                if findings:
                                    for finding in findings:
                                        finding['file'] = filepath
                                    all_findings.extend(findings)
                    except Exception as e:
                        print(f"Error analyzing {filepath}: {str(e)}")

                if GITHUB_TOKEN:
                    post_github_review(repo_name, pr_number, all_findings, GITHUB_TOKEN)
                else:
                    print("No GitHub token, would have posted:")
                    print(json.dumps(all_findings, indent=2))

            finally:
                shutil.rmtree(repo_path, ignore_errors=True)

            sqs.delete_message(
                QueueUrl=QUEUE_URL,
                ReceiptHandle=receipt_handle
            )
            print(f"Successfully processed PR #{pr_number}")

        except Exception as e:
            print(f"Error processing message: {str(e)}")
            raise

    return {
        'statusCode': 200,
        'body': json.dumps('Processing complete')
    }